### ISSUE TITLE
Plan for recurrent soft Q-learning and DRQN?

### ISSUE THREAD

**Issue by hai-h-nguyen** [twni2016/pomdp-baselines#10]
As the title says.

**Comment by twni2016** [comment]
Hi, 

I currently do have plan on DQN-style implementation, as I focus on actor-critic methods, and need to refactor the code for actor-critic into Q-learning. There have been some github repos on DRQN https://github.com/keep9oing/DRQN-Pytorch-CartPole-v1 

Feel free to pull request if you think it worth adding DQN-style methods into this repo.
