### ISSUE TITLE
Potential bug?

### ISSUE THREAD

**Issue by hai-h-nguyen** [twni2016/pomdp-baselines#11]
For SACD, can you explain why you do this 
https://github.com/twni2016/pomdp-baselines/blob/main/policies/models/policy_rnn.py#L235
instead of this (which I think is correct)?
https://github.com/twni2016/pomdp-baselines/blob/main/policies/models/policy_rnn.py#L230

**Comment by twni2016** [comment]
Because the target value V(s') = E_{a'~ \pi(s')}{Q(s',a')}. I think there is no bug?

**Comment by hai-h-nguyen** [comment]
Yeah, it's not a bug. Therefore, I closed the issue. Thanks for replying.
