### ISSUE TITLE
Handle cases when the episode length < 2

### ISSUE THREAD

**Issue by hai-h-nguyen** [twni2016/pomdp-baselines#12]
Hello, 

I wonder do you have any thoughts on how to handle that case? Currently, you assume it never happens and the code will raise an error for such cases. However, in some domains like the MiniGrid Lava Crossing, for instance, that might happen quite often. Thanks!

**Comment by hai-h-nguyen** [comment]
Also, why do you have to extend the actions and the observation in https://github.com/twni2016/pomdp-baselines/blob/819f7c51dff8045c93c6580c90f6e743d6337ba6/policies/models/policy_rnn.py#L383?

**Comment by twni2016** [comment]
> Hello,
> 
> I wonder do you have any thoughts on how to handle that case? Currently, you assume it never happens and the code will raise an error for such cases. However, in some domains like the MiniGrid Lava Crossing, for instance, that might happen quite often. Thanks!

A quick fix is to manually force the episode length >=2, by adding a dummy transition if not.

**Comment by twni2016** [comment]
> Also, why do you have to extend the actions and the observation in
> 
> https://github.com/twni2016/pomdp-baselines/blob/819f7c51dff8045c93c6580c90f6e743d6337ba6/policies/models/policy_rnn.py#L383
> 
> ?

You can check the meaning of these variables in https://github.com/twni2016/pomdp-baselines/blob/main/policies/models/policy_rnn.py#L172

Since at the first timestep, agent only receives initial observation, without previous action and reward, I have to add dummy prev act and rew into the trajectory for training.

**Comment by hai-h-nguyen** [comment]
Thank you!
