### ISSUE TITLE
Same image encoder for RNN and Actor/Critic shortcut?

### ISSUE THREAD

**Issue by RobertMcCarthy97** [twni2016/pomdp-baselines#15]
According to Figure 7 of the paper, separate modules are used to create observation embeddings for the RNN and shortcut observations for the actor/critic MLP head respectively.

However, in the code it appears that the same image encoder is used to create image embeddings for the RNN and MLP (e.g. the same `self.image_encoder` is used in `get_obs_embedding() `and `get_shortcut_obs_embedding()` [here](https://github.com/twni2016/pomdp-baselines/blob/4d9cbf15d488027a146731aa1099944c23901616/policies/models/recurrent_actor.py#L89)).

Was there any reason for this design choice?

**Comment by twni2016** [comment]
Hi, this is a minor detail. In addition, I think using shortcuts or not won't make a difference to performance. Feel free to make your own design.
